# Generated by Django 4.2.3 on 2024-05-30 18:49

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('main_text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Опис')),
                ('tags', models.CharField(max_length=200, verbose_name='Теги')),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата створення')),
            ],
        ),
    ]
