# Generated by Django 4.2.3 on 2024-05-31 00:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, max_length=40, populate_from='title', unique=True),
        ),
    ]
