# Generated by Django 4.2.3 on 2024-06-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articlemodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'verbose_name': 'Стаття', 'verbose_name_plural': 'Статті'},
        ),
    ]
