# Generated by Django 4.2.3 on 2024-09-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_articlemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='article_type',
            field=models.CharField(blank=True, choices=[('Для користувачів', 'user_article'), ('Технічна стаття', 'tech_article')], max_length=30, null=True, verbose_name='Тип статті'),
        ),
    ]
