# Generated by Django 4.2.3 on 2024-09-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articlemodel_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Теги'),
        ),
    ]
