# Generated by Django 4.2.3 on 2024-10-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_articlemodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='article_type',
            field=models.CharField(blank=True, choices=[('user_article', 'Для користувачів'), ('tech_article', 'Технічна стаття')], max_length=30, null=True, verbose_name='Тип статті'),
        ),
    ]
