# Generated by Django 4.2.3 on 2024-04-18 13:17

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='ChargerItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200, null=True, verbose_name='Короткий опис')),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Модель товару',
            },
        ),
        migrations.CreateModel(
            name='ChargersItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Назва')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, max_length=40, populate_from='title', unique=True)),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('small_description', models.TextField(max_length=600, verbose_name='Короткий опис')),
                ('description', models.TextField(verbose_name='Опис')),
                ('power', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Потужність, кВт')),
                ('power_amps', models.IntegerField(blank=True, null=True, verbose_name='Потужність, А')),
                ('phases', models.TextField(blank=True, choices=[('Одна фаза', '1_phase'), ('Три фази', '3_phase')], null=True, verbose_name='Кількість фаз')),
                ('type', models.CharField(blank=True, choices=[('Type 1', 'type_1'), ('Type 2', 'type_2'), ('Type Tesla', 'type_tesla')], max_length=10, null=True, verbose_name="Тип роз'єму")),
                ('cable_length', models.IntegerField(blank=True, null=True, verbose_name='Довжина кабелю')),
                ('protection', models.CharField(blank=True, max_length=10, null=True, verbose_name='Захист корпусу')),
                ('guarantee', models.CharField(blank=True, max_length=10, null=True, verbose_name='Гарантія')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='Бренд')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='Країна-виробник')),
                ('form', models.CharField(blank=True, max_length=15, null=True, verbose_name='Формфактор')),
                ('features', models.TextField(blank=True, max_length=200, null=True, verbose_name='Додаткові функції')),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата створення')),
                ('size', models.CharField(blank=True, max_length=15, null=True, verbose_name='Розмір')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Матеріал')),
                ('in_stock', models.CharField(blank=True, choices=[('True', 'Активно'), ('False', 'Неактивно'), ('pending', 'Під замовлення')], max_length=20, null=True, verbose_name='Наявність')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.chargeritemmodel')),
            ],
            options={
                'verbose_name_plural': 'Зарядні пристрої',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('current', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Поточний курс до Евро')),
                ('token', models.CharField(blank=True, max_length=10, verbose_name='Символ')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, max_length=40, populate_from='title', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name="Ім'я файлу")),
                ('chargersitems', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.chargersitems')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Галерея фото',
                'verbose_name_plural': 'Галерея фото',
            },
        ),
    ]
