# Generated by Django 4.2.3 on 2024-05-01 11:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargersitems',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Опис'),
        ),
    ]
