# Generated by Django 4.2.3 on 2024-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_chargersitems_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargersitems',
            name='accessories_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип аксесуару'),
        ),
    ]
