# Generated by Django 4.2.3 on 2024-05-30 15:09

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_chargersitems_accessories_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargersitems',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Опис'),
        ),
    ]
