# Generated by Django 4.2.3 on 2024-06-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_chargersitems_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargersitems',
            name='product_article',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Артикул'),
        ),
    ]
