# Generated by Django 4.2.3 on 2024-06-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_chargersitems_product_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargersitems',
            name='model',
        ),
        migrations.AddField(
            model_name='chargersitems',
            name='model',
            field=models.ManyToManyField(blank=True, null=True, to='store.chargeritemmodel'),
        ),
    ]
