# Generated by Django 4.2.3 on 2024-06-09 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_chargersitems_model_chargersitems_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargersitems',
            name='model',
        ),
        migrations.AddField(
            model_name='chargersitems',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.chargeritemmodel'),
        ),
    ]
