# Generated by Django 4.2.3 on 2024-06-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_chargersitems_model_chargersitems_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeritemmodel',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Бренд'),
        ),
    ]
