# Generated by Django 4.2.3 on 2024-06-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_chargeritemmodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeritemmodel',
            name='plugs',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Доступні роз'єми"),
        ),
    ]
