# Generated by Django 4.2.3 on 2024-06-18 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_chargeritemmodel_plugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritesProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.chargersitems')),
            ],
            options={
                'verbose_name': 'Обрані товари',
                'verbose_name_plural': 'Обрані товари',
            },
        ),
    ]
