# Generated by Django 4.2.3 on 2024-06-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_favoritesproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoritesProducts',
            new_name='FavoriteProducts',
        ),
    ]
