# Generated by Django 4.2.3 on 2024-06-27 17:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_favoritesproducts_favoriteproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargersitems',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, max_length=100, populate_from='title', unique=True),
        ),
    ]
