# Generated by Django 4.2.3 on 2024-07-04 16:13

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('store', '0013_alter_chargersitems_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeritemmodel',
            name='gif',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_gif', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
