# Generated by Django 4.2.3 on 2024-07-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_chargeritemmodel_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproducts',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.chargeritemmodel'),
        ),
    ]
