# Generated by Django 4.2.3 on 2024-08-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_favoriteproducts_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargersitems',
            name='accessories_type',
            field=models.CharField(blank=True, choices=[('T', 'Тримач конектора'), ('K', 'Кріплення\\Тримач')], max_length=50, null=True, verbose_name='Тип аксесуару'),
        ),
    ]
