# Generated by Django 4.2.3 on 2024-08-04 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_chargersitems_accessories_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteproducts',
            name='accessories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.chargersitems'),
        ),
    ]
