# Generated by Django 4.2.3 on 2024-08-04 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_favoriteproducts_accessories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproducts',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.chargersitems'),
        ),
        migrations.AlterField(
            model_name='favoriteproducts',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.chargeritemmodel'),
        ),
    ]
