# Generated by Django 4.2.3 on 2024-08-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_favoriteproducts_accessories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteproducts',
            name='accessories',
        ),
    ]
