# Generated by Django 4.2.3 on 2024-08-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_favoriteproducts_accessories'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.chargersitems')),
            ],
            options={
                'verbose_name': 'Обрані аксесуари',
                'verbose_name_plural': 'Обрані аксесуари',
            },
        ),
    ]
