# Generated by Django 4.2.3 on 2024-08-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_favoriteaccessories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargersitems',
            name='accessories_type',
            field=models.CharField(blank=True, choices=[('Trimach_conectora', 'Тримач конектора'), ('Kriplennya_trimach', 'Кріплення\\Тримач')], max_length=50, null=True, verbose_name='Тип аксесуару'),
        ),
    ]
