# Generated by Django 4.2.3 on 2024-08-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_chargersitems_accessories_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargersitems',
            name='accessories_type',
            field=models.CharField(blank=True, choices=[('Тримач конектора', 'Trimach_conectora'), ('Кріплення\\Тримач', 'Kriplennya_trimach')], max_length=50, null=True, verbose_name='Тип аксесуару'),
        ),
    ]
