# Generated by Django 4.2.3 on 2024-08-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_chargersitems_accessories_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargersitems',
            name='accessories_type',
            field=models.CharField(blank=True, choices=[('Trimach_conectora', 'Тримач конектора'), ('Kriplennya_trimach', 'Кріплення\\Тримач'), ('electric_adapt', 'Електричні перехідники'), ('auto_adapt', 'Електромобільні перехідники'), ('plugs', 'Розетки'), ('clothes', 'Одяг'), ('other', 'Інше обладнання')], max_length=50, null=True, verbose_name='Тип аксесуару'),
        ),
    ]
