# Generated by Django 4.2.3 on 2024-08-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_chargersitems_accessories_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargersitems',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ціна зі знижкою'),
        ),
    ]
