# Generated by Django 4.2.3 on 2024-08-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_chargersitems_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargersitems',
            name='type',
            field=models.CharField(blank=True, choices=[('Type 1', 'type_1'), ('Type 2', 'type_2'), ('Type Tesla', 'type_tesla'), ('Type GBT', 'type_gbt')], max_length=10, null=True, verbose_name="Тип роз'єму"),
        ),
    ]
