# Generated by Django 4.2.3 on 2024-09-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_chargersitems_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargersitems',
            name='set',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Комплектація'),
        ),
    ]
