# Generated by Django 4.2.3 on 2024-05-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quick_order',
        ),
        migrations.RemoveField(
            model_name='quickorder',
            name='user',
        ),
        migrations.AddField(
            model_name='quickorder',
            name='type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
