# Generated by Django 4.2.3 on 2024-05-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderitem_quick_order_remove_quickorder_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quickorder',
            options={'ordering': ('-created',), 'verbose_name': 'Швидке замовлення і зворотній дзвінок', 'verbose_name_plural': 'Швидкі замовлення і зворотні дзвінки'},
        ),
        migrations.AlterField(
            model_name='quickorder',
            name='type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
