# Generated by Django 4.2.3 on 2024-05-19 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_quickorder_options_alter_quickorder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quick_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.quickorder'),
        ),
    ]
