# Generated by Django 4.2.3 on 2024-05-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_quick_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quickorder',
            old_name='first_name',
            new_name='name',
        ),
    ]
