# Generated by Django 4.2.3 on 2024-05-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_first_name_quickorder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickorder',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
