# Generated by Django 4.2.3 on 2024-05-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_quickorder_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('viber', 'Viber'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Готівка'), ('bank_card', 'Сплата на карту'), ('cashless_payments', 'Безготівковий розрахунок')], default='bank_card', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('self', 'Самовивіз')], default='nova_poshta', max_length=15),
        ),
    ]
