# Generated by Django 4.2.3 on 2024-06-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('self', 'Самовивіз')], max_length=15),
        ),
    ]
