# Generated by Django 4.2.3 on 2024-06-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_shipping_address_alter_order_shipping_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
